name: Run Cypress tests fail
on: [push]
jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: install 
        run: |
          npm i
      - name: passing test
        uses: cypress-io/github-action@v2
        with:
          install: false 
          command: npm run cypress:fail
